### ISSUE TITLE
[BUG] Soft warning if user hasn't run `npm install` after cloning

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-acf-blocks#18]
@asharirfan I installed the plugin and activated and was greeted with a white screen of death.

On this line https://github.com/WebDevStudios/wds-acf-blocks/blob/main/inc/scripts.php#L22 can we run a conditional check for the `/build/` diretory first? 

If it's not there, can we tell the user to go run `npm install` vs. getting a PHP error?

Thanks

**Comment by asharirfan** [comment]
I agree. Intentionally throwing white screen of death is a bad way to show the warning. I will work on fixing this workflow.
