### ISSUE TITLE
Some minor TODOS - Before plugin RC

### ISSUE THREAD

**Issue by bplv112** [WebDevStudios/wds-acf-blocks#32]
- [x] add print_post_taxonomies to wd_s (went missing somehow?)
- [x] add .nvmrc to the plugin so that it’s easy to use the correct node version (14, I think?)
- [x] add .vscode folder with configs
- [x] fix phpcs issues (error code 2 on npm run lint

**Comment by bplv112** [comment]
https://github.com/WebDevStudios/wd_s/pull/935 - Taxonomy function helper added. 

https://github.com/WebDevStudios/wds-acf-blocks/commit/26080fd54ec7c2ad9e932fdcd246b55259482d55 - Lint fixes

https://github.com/WebDevStudios/wds-acf-blocks/commit/5216234d677831eb160c4f8afb6526212897f914 - Nvmrc and vscode config added.

**Comment by oliverharrison** [comment]
Thanks for your work on this - closing.
