### ISSUE TITLE
Block Testing

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wds-acf-blocks#4]
Please test these blocks with the latest version of the ACF Pro and the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/).

- [x] Accordion
- [x] Call To Action
- [x] Carousel
- [x] Fifty/Fifty
- [x] Hero
- [x] Recent Posts
- [x] Related Posts

Feel free to log any issues as Github issues (set the milestone to 1.0.0), so we can work through them.

**Comment by asharirfan** [comment]
I have done the testing and found the following two issues in the plugin:

- [ ] #9 
- [ ] #10

**Comment by asharirfan** [comment]
EOD Update:

- Tested all the blocks and fixed minor styling issues
